application: tomochikahara
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true

automatic_scaling:
  max_idle_instances: 1

handlers:
- url: /.*
  script: helloworld.route.APP
